/*
*SPDX-FileCopyrightText: Copyright 2020 | Regione Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

package it.csi.portril.portrilweb.business.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-10-09T15:41:33.312+02:00
 * Generated source version: 2.7.7
 * 
 */
public final class BilancioWsInterface_BilancioWsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.bilancio.interfacecxf.cmpsrvrp.bilsrvrp.csi.it/", "BilancioWsService");

    private BilancioWsInterface_BilancioWsPort_Client() {
    }
/*
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BilancioWsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BilancioWsService ss = new BilancioWsService(wsdlURL, SERVICE_NAME);
        BilancioWsInterface port = ss.getBilancioWsPort();  
        
        
        {
        System.out.println("Invoking consultaLiquidazioniByAtto...");
        it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO _consultaLiquidazioniByAtto_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO _consultaLiquidazioniByAtto__return = port.consultaLiquidazioniByAtto(_consultaLiquidazioniByAtto_arg0);
            System.out.println("consultaLiquidazioniByAtto.result=" + _consultaLiquidazioniByAtto__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaCapitoliXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO _consultaCapitoliXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO _consultaCapitoliXImpegni__return = port.consultaCapitoliXImpegni(_consultaCapitoliXImpegni_arg0);
            System.out.println("consultaCapitoliXImpegni.result=" + _consultaCapitoliXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaDirezioniAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO _consultaDirezioniAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO _consultaDirezioniAll__return = port.consultaDirezioniAll(_consultaDirezioniAll_arg0);
            System.out.println("consultaDirezioniAll.result=" + _consultaDirezioniAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaCodiciGestionaliAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO _consultaCodiciGestionaliAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO _consultaCodiciGestionaliAll__return = port.consultaCodiciGestionaliAll(_consultaCodiciGestionaliAll_arg0);
            System.out.println("consultaCodiciGestionaliAll.result=" + _consultaCodiciGestionaliAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaFornitoriAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO _consultaFornitoriAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO _consultaFornitoriAll__return = port.consultaFornitoriAll(_consultaFornitoriAll_arg0);
            System.out.println("consultaFornitoriAll.result=" + _consultaFornitoriAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking determinaByCodice...");
        it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO _determinaByCodice_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO _determinaByCodice__return = port.determinaByCodice(_determinaByCodice_arg0);
            System.out.println("determinaByCodice.result=" + _determinaByCodice__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaMandatiCodGestAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO _consultaMandatiCodGestAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO _consultaMandatiCodGestAll__return = port.consultaMandatiCodGestAll(_consultaMandatiCodGestAll_arg0);
            System.out.println("consultaMandatiCodGestAll.result=" + _consultaMandatiCodGestAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaImpegniAmmAperta...");
        it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO _consultaImpegniAmmAperta_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO _consultaImpegniAmmAperta__return = port.consultaImpegniAmmAperta(_consultaImpegniAmmAperta_arg0);
            System.out.println("consultaImpegniAmmAperta.result=" + _consultaImpegniAmmAperta__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaCapitoliAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO _consultaCapitoliAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO _consultaCapitoliAll__return = port.consultaCapitoliAll(_consultaCapitoliAll_arg0);
            System.out.println("consultaCapitoliAll.result=" + _consultaCapitoliAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaAttoLiquidazione...");
        it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO _consultaAttoLiquidazione_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO _consultaAttoLiquidazione__return = port.consultaAttoLiquidazione(_consultaAttoLiquidazione_arg0);
            System.out.println("consultaAttoLiquidazione.result=" + _consultaAttoLiquidazione__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaMandatiByAtto...");
        it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO _consultaMandatiByAtto_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO _consultaMandatiByAtto__return = port.consultaMandatiByAtto(_consultaMandatiByAtto_arg0);
            System.out.println("consultaMandatiByAtto.result=" + _consultaMandatiByAtto__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaDetermineXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO _consultaDetermineXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO _consultaDetermineXImpegni__return = port.consultaDetermineXImpegni(_consultaDetermineXImpegni_arg0);
            System.out.println("consultaDetermineXImpegni.result=" + _consultaDetermineXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaImpegniByAnnoEsercizio...");
        it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO _consultaImpegniByAnnoEsercizio_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO _consultaImpegniByAnnoEsercizio__return = port.consultaImpegniByAnnoEsercizio(_consultaImpegniByAnnoEsercizio_arg0);
            System.out.println("consultaImpegniByAnnoEsercizio.result=" + _consultaImpegniByAnnoEsercizio__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaDelibereXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO _consultaDelibereXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO _consultaDelibereXImpegni__return = port.consultaDelibereXImpegni(_consultaDelibereXImpegni_arg0);
            System.out.println("consultaDelibereXImpegni.result=" + _consultaDelibereXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaAttiLiquidazione...");
        it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO _consultaAttiLiquidazione_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO _consultaAttiLiquidazione__return = port.consultaAttiLiquidazione(_consultaAttiLiquidazione_arg0);
            System.out.println("consultaAttiLiquidazione.result=" + _consultaAttiLiquidazione__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaMandatiAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO _consultaMandatiAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO _consultaMandatiAll__return = port.consultaMandatiAll(_consultaMandatiAll_arg0);
            System.out.println("consultaMandatiAll.result=" + _consultaMandatiAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificaMandatiByAtto...");
        it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO _verificaMandatiByAtto_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO _verificaMandatiByAtto__return = port.verificaMandatiByAtto(_verificaMandatiByAtto_arg0);
            System.out.println("verificaMandatiByAtto.result=" + _verificaMandatiByAtto__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaFornitoriXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO _consultaFornitoriXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO _consultaFornitoriXImpegni__return = port.consultaFornitoriXImpegni(_consultaFornitoriXImpegni_arg0);
            System.out.println("consultaFornitoriXImpegni.result=" + _consultaFornitoriXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deliberaByCodice...");
        it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO _deliberaByCodice_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO _deliberaByCodice__return = port.deliberaByCodice(_deliberaByCodice_arg0);
            System.out.println("deliberaByCodice.result=" + _deliberaByCodice__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaDirezioniXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO _consultaDirezioniXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO _consultaDirezioniXImpegni__return = port.consultaDirezioniXImpegni(_consultaDirezioniXImpegni_arg0);
            System.out.println("consultaDirezioniXImpegni.result=" + _consultaDirezioniXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking inserisciAttoLiquidazione...");
        it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO _inserisciAttoLiquidazione_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO _inserisciAttoLiquidazione__return = port.inserisciAttoLiquidazione(_inserisciAttoLiquidazione_arg0);
            System.out.println("inserisciAttoLiquidazione.result=" + _inserisciAttoLiquidazione__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaImpegniAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO _consultaImpegniAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO _consultaImpegniAll__return = port.consultaImpegniAll(_consultaImpegniAll_arg0);
            System.out.println("consultaImpegniAll.result=" + _consultaImpegniAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaLiquidazioniAll...");
        it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO _consultaLiquidazioniAll_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO _consultaLiquidazioniAll__return = port.consultaLiquidazioniAll(_consultaLiquidazioniAll_arg0);
            System.out.println("consultaLiquidazioniAll.result=" + _consultaLiquidazioniAll__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO _consultaImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO _consultaImpegni__return = port.consultaImpegni(_consultaImpegni_arg0);
            System.out.println("consultaImpegni.result=" + _consultaImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaMandatiXImpegni...");
        it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO _consultaMandatiXImpegni_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO _consultaMandatiXImpegni__return = port.consultaMandatiXImpegni(_consultaMandatiXImpegni_arg0);
            System.out.println("consultaMandatiXImpegni.result=" + _consultaMandatiXImpegni__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking verificaMandati...");
        it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO _verificaMandati_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO _verificaMandati__return = port.verificaMandati(_verificaMandati_arg0);
            System.out.println("verificaMandati.result=" + _verificaMandati__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultaBeneficiari...");
        it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO _consultaBeneficiari_arg0 = null;
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO _consultaBeneficiari__return = port.consultaBeneficiari(_consultaBeneficiari_arg0);
            System.out.println("consultaBeneficiari.result=" + _consultaBeneficiari__return);

        } catch (CSIException_Exception e) { 
            System.out.println("Expected exception: CSIException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }
*/
}
