/*
*SPDX-FileCopyrightText: Copyright 2020 | Regione Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.portril.portrilweb.business.ws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-10-09T15:43:49.877+02:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "BilancioWsService", 
					wsdlLocation = "classpath:wsdl/BilancioWs.wsdl",
//wsdlLocation = "file:/D:/myworkspace/PORTALE%20RILEVAZIONI/portrilweb/src/resources/wsdl/BilancioWs.wsdl",
                  targetNamespace = "http://cxf.bilancio.interfacecxf.cmpsrvrp.bilsrvrp.csi.it/") 
public class BilancioWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.bilancio.interfacecxf.cmpsrvrp.bilsrvrp.csi.it/", "BilancioWsService");
    public final static QName BilancioWsPort = new QName("http://cxf.bilancio.interfacecxf.cmpsrvrp.bilsrvrp.csi.it/", "BilancioWsPort");
	static {
		WSDL_LOCATION = BilancioWsService.class.getClassLoader().getResource("wsdl/bilancio-cre--BILANCIO_bilsrvrp_cmpsrvrp1.4.wsdl");
	}

    public BilancioWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BilancioWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BilancioWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns BilancioWsInterface
     */
    @WebEndpoint(name = "BilancioWsPort")
    public BilancioWsInterface getBilancioWsPort() {
        return super.getPort(BilancioWsPort, BilancioWsInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BilancioWsInterface
     */
    @WebEndpoint(name = "BilancioWsPort")
    public BilancioWsInterface getBilancioWsPort(WebServiceFeature... features) {
        return super.getPort(BilancioWsPort, BilancioWsInterface.class, features);
    }

}
