/*
*SPDX-FileCopyrightText: Copyright 2020 | Regione Piemonte
*SPDX-License-Identifier: EUPL-1.2
*/

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.csi.portril.portrilweb.business.ws;

import it.csi.portril.portrilweb.util.LogUtil;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-10-09T15:41:33.442+02:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "BilancioWsService",
                      portName = "BilancioWsPort",
                      targetNamespace = "http://cxf.bilancio.interfacecxf.cmpsrvrp.bilsrvrp.csi.it/",
                    		  wsdlLocation = "classpath:wsdl/BilancioWs.wsdl",
                    		  //wsdlLocation = "file:/D:/myworkspace/PORTALE%20RILEVAZIONI/portrilweb/src/resources/wsdl/BilancioWs.wsdl",
                      endpointInterface = "it.csi.portril.portrilweb.business.ws.BilancioWsInterface")
                      
public class BilancioWsInterfaceImpl implements BilancioWsInterface {

    //private static final Logger LOG = Logger.getLogger(BilancioWsInterfaceImpl.class.getName());
    LogUtil log = new LogUtil(getClass());

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaLiquidazioniByAtto(it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO consultaLiquidazioniByAtto(it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaLiquidazioniByAtto";
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniByAttoDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	
			log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaCapitoliXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO consultaCapitoliXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "ConsultaCapitoliXImpegniDTO";

        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCapitoliXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...";
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaDirezioniAll(it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO consultaDirezioniAll(it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaDirezioniAll";
        ////System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDirezioniAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaCodiciGestionaliAll(it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO consultaCodiciGestionaliAll(it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaCodiciGestionaliAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCodiciGestionaliAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaFornitoriAll(it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO consultaFornitoriAll(it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaFornitoriAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaFornitoriAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#determinaByCodice(it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO determinaByCodice(it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO arg0) throws CSIException_Exception    { 
        String methodName = "determinaByCodice";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.DeterminaByCodiceDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaMandatiCodGestAll(it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO consultaMandatiCodGestAll(it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaMandatiCodGestAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiCodGestAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaImpegniAmmAperta(it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO consultaImpegniAmmAperta(it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaImpegniAmmAperta";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniAmmApertaDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaCapitoliAll(it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO consultaCapitoliAll(it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaCapitoliAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaCapitoliAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaAttoLiquidazione(it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO consultaAttoLiquidazione(it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaAttoLiquidazione";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaAttoLiquidazioneDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaMandatiByAtto(it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO consultaMandatiByAtto(it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaMandatiByAtto";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiByAttoDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaDetermineXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO consultaDetermineXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaDetermineXImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDetermineXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaImpegniByAnnoEsercizio(it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO consultaImpegniByAnnoEsercizio(it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaImpegniByAnnoEsercizio";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniByAnnoEsercizioDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaDelibereXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO consultaDelibereXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaDelibereXImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDelibereXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaAttiLiquidazione(it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO consultaAttiLiquidazione(it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaAttiLiquidazione";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaAttiLiquidazioneDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaMandatiAll(it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO consultaMandatiAll(it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaMandatiAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#verificaMandatiByAtto(it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO verificaMandatiByAtto(it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO arg0) throws CSIException_Exception    { 
        String methodName = "verificaMandatiByAtto";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.VerificaMandatiByAttoDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaFornitoriXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO consultaFornitoriXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaFornitoriXImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaFornitoriXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#deliberaByCodice(it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO deliberaByCodice(it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO arg0) throws CSIException_Exception    { 
        String methodName = "deliberaByCodice";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.DeliberaByCodiceDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaDirezioniXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO consultaDirezioniXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaDirezioniXImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaDirezioniXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#inserisciAttoLiquidazione(it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO inserisciAttoLiquidazione(it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO arg0) throws CSIException_Exception    { 
        String methodName = "inserisciAttoLiquidazione";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.InserisciAttoLiquidazioneDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaImpegniAll(it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO consultaImpegniAll(it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaImpegniAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaLiquidazioniAll(it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO consultaLiquidazioniAll(it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaLiquidazioniAll";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaLiquidazioniAllDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaImpegni(it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO consultaImpegni(it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaMandatiXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO consultaMandatiXImpegni(it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaMandatiXImpegni";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaMandatiXImpegniDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#verificaMandati(it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO verificaMandati(it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO arg0) throws CSIException_Exception    { 
        String methodName = "verificaMandati";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.VerificaMandatiDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

    /* (non-Javadoc)
     * @see it.csi.portril.portrilweb.business.ws.BilancioWsInterface#consultaBeneficiari(it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO  arg0 )*
     */
    public it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO consultaBeneficiari(it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO arg0) throws CSIException_Exception    { 
        String methodName = "consultaBeneficiari";
        //System.out.println(arg0);
        try {
            it.csi.portril.portrilweb.business.ws.ConsultaBeneficiariDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
        	log.error(methodName, ex);
            throw new RuntimeException(ex);
        }
        //throw new CSIException_Exception("CSIException...");
    }

}
